const KEY='oficinaClubDB_v1';
const defaults={empresa:{nome:'Oficina Club',descricao:'Peças, Serviços e Acessórios',cnpj:'17.294.997/0001-32',telefone:'(16) 99374-1409',email:'oficinaclub@outlook.com',endereco:'Área Rural, Rodovia Cravinhos a Bonfim',cidade:'Cravinhos/SP'},clientes:[],veiculos:[],produtos:[],ordens:[]};
let db=load();let itensTemp=[];
function load(){try{return {...structuredClone(defaults),...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return structuredClone(defaults)}}
function save(){localStorage.setItem(KEY,JSON.stringify(db));renderAll()}
const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const id=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,7);
const cliente=i=>db.clientes.find(x=>x.id===i)||{};const veiculo=i=>db.veiculos.find(x=>x.id===i)||{};
function table(headers,rows){return rows.length?`<table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table>`:'<div class="empty">Nenhum registro cadastrado.</div>'}
function renderAll(){renderSelects();renderClientes();renderVeiculos();renderProdutos();renderOS();renderDashboard();renderEmpresa()}
function renderSelects(){const cs=db.clientes.map(x=>`<option value="${x.id}">${esc(x.nome)}</option>`).join('');document.querySelectorAll('select[name="clienteId"]').forEach(s=>{const old=s.value;s.innerHTML='<option value="">Selecione</option>'+cs;s.value=old});const cat=db.produtos.map(x=>`<option value="${x.id}">${esc(x.tipo)} - ${esc(x.descricao)} (${money(x.preco)})</option>`).join('');itemCatalogo.innerHTML='<option value="">Selecione um item</option>'+cat}
function renderClientes(q=''){q=q.toLowerCase();const a=db.clientes.filter(x=>[x.nome,x.telefone,x.documento].join(' ').toLowerCase().includes(q));listaClientes.innerHTML=table(['Nome','Telefone','Documento',''],a.map(x=>`<tr><td>${esc(x.nome)}</td><td>${esc(x.telefone)}</td><td>${esc(x.documento)}</td><td><button class="danger mini-btn" onclick="del('clientes','${x.id}')">Excluir</button></td></tr>`))}
function renderVeiculos(q=''){q=q.toLowerCase();const a=db.veiculos.filter(x=>[x.placa,x.marca,x.modelo].join(' ').toLowerCase().includes(q));listaVeiculos.innerHTML=table(['Placa','Veículo','Cliente','KM',''],a.map(x=>`<tr><td><strong>${esc(x.placa)}</strong></td><td>${esc(x.marca)} ${esc(x.modelo)} ${esc(x.ano)}</td><td>${esc(cliente(x.clienteId).nome)}</td><td>${esc(x.km)}</td><td><button class="danger mini-btn" onclick="del('veiculos','${x.id}')">Excluir</button></td></tr>`))}
function renderProdutos(q=''){q=q.toLowerCase();const a=db.produtos.filter(x=>[x.descricao,x.codigo,x.tipo].join(' ').toLowerCase().includes(q));listaProdutos.innerHTML=table(['Tipo','Código','Descrição','Preço','Estoque',''],a.map(x=>`<tr><td><span class="badge">${esc(x.tipo)}</span></td><td>${esc(x.codigo)}</td><td>${esc(x.descricao)}</td><td>${money(x.preco)}</td><td>${x.tipo==='Peça'?esc(x.estoque):'-'}</td><td><button class="danger mini-btn" onclick="del('produtos','${x.id}')">Excluir</button></td></tr>`))}
function renderOS(q=''){q=q.toLowerCase();const a=[...db.ordens].reverse().filter(x=>[x.numero,cliente(x.clienteId).nome,veiculo(x.veiculoId).placa,x.status].join(' ').toLowerCase().includes(q));listaOS.innerHTML=table(['OS','Data','Cliente / veículo','Status','Total',''],a.map(x=>`<tr><td><strong>#${x.numero}</strong></td><td>${new Date(x.data).toLocaleDateString('pt-BR')}</td><td>${esc(cliente(x.clienteId).nome)}<br><small>${esc(veiculo(x.veiculoId).placa)} - ${esc(veiculo(x.veiculoId).modelo)}</small></td><td><span class="badge">${esc(x.status)}</span></td><td>${money(x.total)}</td><td class="nowrap"><button class="secondary mini-btn" onclick="printOS('${x.id}')">Imprimir</button> <button class="danger mini-btn" onclick="del('ordens','${x.id}')">Excluir</button></td></tr>`))}
function renderDashboard(){kpiAbertas.textContent=db.ordens.filter(x=>['Aberta','Em diagnóstico','Aguardando aprovação','Aprovada'].includes(x.status)).length;kpiExecucao.textContent=db.ordens.filter(x=>x.status==='Em execução').length;kpiFinalizadas.textContent=db.ordens.filter(x=>['Finalizada','Entregue'].includes(x.status)).length;kpiValor.textContent=money(db.ordens.filter(x=>x.status!=='Cancelada').reduce((s,x)=>s+Number(x.total),0));const a=[...db.ordens].reverse().slice(0,5);recentes.innerHTML=table(['OS','Cliente','Placa','Status','Total'],a.map(x=>`<tr><td>#${x.numero}</td><td>${esc(cliente(x.clienteId).nome)}</td><td>${esc(veiculo(x.veiculoId).placa)}</td><td><span class="badge">${esc(x.status)}</span></td><td>${money(x.total)}</td></tr>`))}
function renderEmpresa(){Object.entries(db.empresa).forEach(([k,v])=>{if(empresaForm.elements[k])empresaForm.elements[k].value=v})}
window.del=(tipo,i)=>{if(confirm('Confirma a exclusão?')){db[tipo]=db[tipo].filter(x=>x.id!==i);save()}};
document.querySelectorAll('.nav-btn').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav-btn,.page').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById(b.dataset.page).classList.add('active')});
document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.open).showModal());document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());document.querySelectorAll('[data-open-os]').forEach(b=>b.onclick=()=>{if(!db.clientes.length||!db.veiculos.length){alert('Cadastre primeiro um cliente e um veículo.');return}itensTemp=[];renderItens();osDialog.showModal()});
clienteForm.onsubmit=e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.target));db.clientes.push({id:id(),...o});save();e.target.reset();clienteDialog.close()};
veiculoForm.onsubmit=e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.target));o.placa=o.placa.toUpperCase();db.veiculos.push({id:id(),...o});save();e.target.reset();veiculoDialog.close()};
produtoForm.onsubmit=e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.target));o.preco=Number(o.preco);o.estoque=Number(o.estoque);db.produtos.push({id:id(),...o});save();e.target.reset();produtoDialog.close()};
empresaForm.onsubmit=e=>{e.preventDefault();db.empresa=Object.fromEntries(new FormData(e.target));save();alert('Dados salvos.')};
osForm.elements.clienteId.onchange=e=>{const vs=db.veiculos.filter(v=>v.clienteId===e.target.value);osForm.elements.veiculoId.innerHTML='<option value="">Selecione</option>'+vs.map(v=>`<option value="${v.id}">${esc(v.placa)} - ${esc(v.marca)} ${esc(v.modelo)}</option>`).join('')};
addItem.onclick=()=>{const p=db.produtos.find(x=>x.id===itemCatalogo.value);if(!p)return;itensTemp.push({id:id(),produtoId:p.id,tipo:p.tipo,descricao:p.descricao,qtd:Number(itemQtd.value||1),preco:Number(p.preco)});renderItens()};
function renderItens(){itensOS.innerHTML=table(['Item','Qtd.','Unitário','Total',''],itensTemp.map(x=>`<tr><td>${esc(x.descricao)}</td><td>${x.qtd}</td><td>${money(x.preco)}</td><td>${money(x.qtd*x.preco)}</td><td><button type="button" class="danger mini-btn" onclick="remItem('${x.id}')">Remover</button></td></tr>`));totalOS.textContent=money(itensTemp.reduce((s,x)=>s+x.qtd*x.preco,0))}
window.remItem=i=>{itensTemp=itensTemp.filter(x=>x.id!==i);renderItens()};
osForm.onsubmit=e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.target));const numero=String((Math.max(0,...db.ordens.map(x=>Number(x.numero)))+1)).padStart(5,'0');const total=itensTemp.reduce((s,x)=>s+x.qtd*x.preco,0);db.ordens.push({id:id(),numero,data:new Date().toISOString(),...o,itens:itensTemp,total});itensTemp.filter(x=>x.tipo==='Peça').forEach(i=>{const p=db.produtos.find(p=>p.id===i.produtoId);if(p)p.estoque=Math.max(0,Number(p.estoque)-i.qtd)});save();e.target.reset();itensTemp=[];osDialog.close()};
[buscaCliente,buscaVeiculo,buscaProduto,buscaOS].forEach((x,i)=>x.oninput=()=>[renderClientes,renderVeiculos,renderProdutos,renderOS][i](x.value));
backupBtn.onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(db,null,2)],{type:'application/json'}));a.download='backup-oficina-club.json';a.click();URL.revokeObjectURL(a.href)};
window.printOS=i=>{const o=db.ordens.find(x=>x.id===i),c=cliente(o.clienteId),v=veiculo(o.veiculoId),e=db.empresa;const itens=o.itens.map(x=>`<tr><td>${esc(x.descricao)}</td><td>${x.qtd}</td><td>${money(x.preco)}</td><td>${money(x.qtd*x.preco)}</td></tr>`).join('');const w=open('','_blank');w.document.write(`<!doctype html><html><head><title>OS ${o.numero}</title><style>body{font-family:Arial;margin:30px;color:#111}header{border-bottom:3px solid #111;padding-bottom:12px}h1{margin:0}.meta{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin:20px 0}.box{border:1px solid #bbb;padding:12px;border-radius:6px}table{width:100%;border-collapse:collapse}th,td{border:1px solid #bbb;padding:8px;text-align:left}.total{text-align:right;font-size:20px;margin-top:15px}.sign{display:grid;grid-template-columns:1fr 1fr;gap:40px;margin-top:70px}.sign div{border-top:1px solid #111;text-align:center;padding-top:6px}@media print{button{display:none}}</style></head><body><header><h1>${esc(e.nome)}</h1><div>${esc(e.descricao)}</div><small>CNPJ ${esc(e.cnpj)} | ${esc(e.telefone)} | ${esc(e.email)}<br>${esc(e.endereco)} - ${esc(e.cidade)}</small></header><h2>ORDEM DE SERVIÇO Nº ${o.numero}</h2><div class="meta"><div class="box"><strong>Cliente</strong><br>${esc(c.nome)}<br>${esc(c.telefone)}<br>${esc(c.documento)}</div><div class="box"><strong>Veículo</strong><br>${esc(v.placa)} - ${esc(v.marca)} ${esc(v.modelo)}<br>Ano: ${esc(v.ano)} | KM: ${esc(v.km)}</div></div><div class="box"><strong>Reclamação:</strong><br>${esc(o.reclamacao)}</div><br><div class="box"><strong>Diagnóstico/observações:</strong><br>${esc(o.diagnostico)}</div><h3>Peças e serviços</h3><table><thead><tr><th>Descrição</th><th>Qtd.</th><th>Unitário</th><th>Total</th></tr></thead><tbody>${itens}</tbody></table><div class="total"><strong>Total: ${money(o.total)}</strong></div><p>Status: ${esc(o.status)} | Emissão: ${new Date(o.data).toLocaleString('pt-BR')}</p><div class="sign"><div>Responsável pela oficina</div><div>Cliente</div></div><script>window.onload=()=>window.print()<\/script></body></html>`);w.document.close()};
renderAll();