const supabaseClient = window.supabase.createClient(window.SUPABASE_URL, window.SUPABASE_ANON_KEY);
let db={empresa:{nome:'Oficina Club',descricao:'Peças, Serviços e Acessórios',cnpj:'17.294.997/0001-32',telefone:'(16) 99374-1409',email:'oficinaclub@outlook.com',endereco:'Área Rural, Rodovia Cravinhos a Bonfim',cidade:'Cravinhos/SP'},clientes:[],veiculos:[],produtos:[],ordens:[],historicos:[]},itensTemp=[],currentUser=null,editingOrderId=null;
const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c])),id=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,7),todayStamp=()=>new Date().toISOString().slice(0,10),dateBR=v=>v?new Date(v).toLocaleDateString('pt-BR'):'';
const cliente=i=>db.clientes.find(x=>x.id===i)||{},veiculo=i=>db.veiculos.find(x=>x.id===i)||{};
const nomeCliente=o=>o.cliente_nome||cliente(o.cliente_id).nome||'Não informado';
const telefoneCliente=o=>o.cliente_telefone||cliente(o.cliente_id).telefone||'';
const documentoCliente=o=>o.cliente_documento||cliente(o.cliente_id).documento||'';
const dadosVeiculo=o=>{const v=veiculo(o.veiculo_id);return {placa:o.placa_avulsa||v.placa||'',marca:o.marca_avulsa||v.marca||'',modelo:o.modelo_avulso||v.modelo||'',ano:o.ano_avulso||v.ano||'',km:o.km_avulsa||v.km||''}};
const getServicos=()=>itensTemp.filter(x=>x.tipo==='Serviço');
const getProdutos=()=>itensTemp.filter(x=>x.tipo==='Peça');
const totalServicosValue=()=>getServicos().reduce((s,x)=>s+x.qtd*x.preco,0);
const totalProdutosValue=()=>getProdutos().reduce((s,x)=>s+x.qtd*x.preco,0);
const descontoServicosPercent=()=>Math.min(100,Math.max(0,Number(descontoServicosPercentual.value||0)));
const descontoProdutosPercent=()=>Math.min(100,Math.max(0,Number(descontoProdutosPercentual.value||0)));
const descontoServicosValue=()=>totalServicosValue()*(descontoServicosPercent()/100);
const descontoProdutosValue=()=>totalProdutosValue()*(descontoProdutosPercent()/100);
const totalGeralValue=()=>Math.max(0,totalServicosValue()-descontoServicosValue()+totalProdutosValue()-descontoProdutosValue());
const valorParcelaValue=()=>{const parcelas=Math.max(1,Number(parcelasOS.value||1));return totalGeralValue()/parcelas};
function table(h,r){return r.length?`<table><thead><tr>${h.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${r.join('')}</tbody></table>`:'<div class="empty">Nenhum registro cadastrado.</div>'}
function nextNumeroOS(){return String(Math.max(0,...db.ordens.map(x=>Number(x.numero)||0))+1).padStart(5,'0')}
async function refreshData(){syncStatus.textContent='Sincronizando...';const [empresaRes,clientesRes,veiculosRes,produtosRes,ordensRes,historicosRes]=await Promise.all([supabaseClient.from('empresas').select('*').limit(1).maybeSingle(),supabaseClient.from('clientes').select('*').order('nome'),supabaseClient.from('veiculos').select('*').order('criado_em'),supabaseClient.from('produtos').select('*').order('descricao'),supabaseClient.from('ordens_servico').select('*, itens_ordem_servico(*)').order('criado_em',{ascending:false}),supabaseClient.from('historico_ordens').select('*').order('criado_em',{ascending:false})]);if([empresaRes,clientesRes,veiculosRes,produtosRes,ordensRes,historicosRes].some(x=>x.error)){syncStatus.textContent='Erro de sincronização';alert('Não foi possível carregar os dados online.');return}db.empresa=empresaRes.data||db.empresa;db.clientes=clientesRes.data||[];db.veiculos=veiculosRes.data||[];db.produtos=produtosRes.data||[];db.ordens=(ordensRes.data||[]).map(o=>({...o,itens:o.itens_ordem_servico||[]}));db.historicos=historicosRes.data||[];renderAll();syncStatus.textContent='Online e sincronizado';}
function renderAll(){renderSelects();renderClientes();renderVeiculos();renderProdutos();renderOS();renderDashboard();renderEmpresa()}
function renderSelects(){const cs=db.clientes.map(x=>`<option value="${x.id}">${esc(x.nome)}</option>`).join('');document.querySelectorAll('select[name="clienteId"]').forEach(s=>{const old=s.value;s.innerHTML='<option value="">Preencher diretamente</option>'+cs;s.value=old});const servicos=db.produtos.filter(x=>x.ativo!==false&&x.tipo==='Serviço');const produtos=db.produtos.filter(x=>x.ativo!==false&&x.tipo==='Peça');itemCatalogoServico.innerHTML='<option value="">Selecione um serviço cadastrado</option>'+servicos.map(x=>`<option value="${x.id}">${esc(x.descricao)} (${money(x.preco)})</option>`).join('');itemCatalogoProduto.innerHTML='<option value="">Selecione um produto cadastrado</option>'+produtos.map(x=>`<option value="${x.id}">${esc(x.descricao)} (${money(x.preco)})</option>`).join('')}
function renderClientes(q=''){q=q.toLowerCase();listaClientes.innerHTML=table(['Nome','Telefone','Documento'],db.clientes.filter(x=>[x.nome,x.telefone,x.documento].join(' ').toLowerCase().includes(q)).map(x=>`<tr><td>${esc(x.nome)}</td><td>${esc(x.telefone)}</td><td>${esc(x.documento)}</td></tr>`))}
function renderVeiculos(q=''){q=q.toLowerCase();listaVeiculos.innerHTML=table(['Placa','Veículo','Cliente','KM'],db.veiculos.filter(x=>[x.placa,x.marca,x.modelo].join(' ').toLowerCase().includes(q)).map(x=>`<tr><td><strong>${esc(x.placa)}</strong></td><td>${esc(x.marca)} ${esc(x.modelo)} ${esc(x.ano)}</td><td>${esc(cliente(x.cliente_id).nome)}</td><td>${esc(x.km)}</td></tr>`))}
function renderProdutos(q=''){q=q.toLowerCase();listaProdutos.innerHTML=table(['Tipo','Código','Descrição','Preço','Estoque'],db.produtos.filter(x=>[x.descricao,x.codigo,x.tipo].join(' ').toLowerCase().includes(q)).map(x=>`<tr><td><span class="badge">${esc(x.tipo)}</span></td><td>${esc(x.codigo)}</td><td>${esc(x.descricao)}</td><td>${money(x.preco)}</td><td>${x.tipo==='Peça'?esc(x.estoque):'-'}</td></tr>`))}
function activeOrders(){return db.ordens.filter(o=>o.status!=='Excluída')}
function renderOS(q=''){q=q.toLowerCase();listaOS.innerHTML=table(['OS','Data','Cliente / veículo','Status','Total',''],activeOrders().filter(o=>[o.numero,nomeCliente(o),dadosVeiculo(o).placa,dadosVeiculo(o).modelo,o.status].join(' ').toLowerCase().includes(q)).map(o=>`<tr><td><strong>#${o.numero}</strong></td><td>${dateBR(o.criado_em)}</td><td>${esc(nomeCliente(o))}<br><small>${esc(dadosVeiculo(o).placa||'Sem placa')} - ${esc(dadosVeiculo(o).modelo||dadosVeiculo(o).marca||'Veículo não informado')}</small></td><td><select class="status-select" onchange="updateStatus('${o.id}', this.value)"><option ${o.status==='Aberta'?'selected':''}>Aberta</option><option ${o.status==='Em diagnóstico'?'selected':''}>Em diagnóstico</option><option ${o.status==='Aguardando aprovação'?'selected':''}>Aguardando aprovação</option><option ${o.status==='Aprovada'?'selected':''}>Aprovada</option><option ${o.status==='Em execução'?'selected':''}>Em execução</option><option ${o.status==='Finalizada'?'selected':''}>Finalizada</option><option ${o.status==='Entregue'?'selected':''}>Entregue</option><option ${o.status==='Cancelada'?'selected':''}>Cancelada</option><option ${o.status==='Enviada'?'selected':''}>Enviada</option></select></td><td>${money(o.total)}</td><td class="nowrap"><button class="secondary mini-btn" onclick="openEditOS('${o.id}')">Editar</button> <button class="secondary mini-btn" onclick="duplicateOS('${o.id}')">Duplicar</button> <button class="danger mini-btn" onclick="deleteOS('${o.id}')">Excluir</button> <button class="secondary mini-btn" onclick="printOS('${o.id}')">Imprimir</button></td></tr>`))}
function renderDashboard(){kpiAbertas.textContent=activeOrders().filter(x=>['Aberta','Em diagnóstico','Aguardando aprovação','Aprovada'].includes(x.status)).length;kpiExecucao.textContent=activeOrders().filter(x=>x.status==='Em execução').length;kpiFinalizadas.textContent=activeOrders().filter(x=>['Finalizada','Entregue'].includes(x.status)).length;kpiValor.textContent=money(activeOrders().filter(x=>x.status!=='Cancelada').reduce((s,x)=>s+Number(x.total),0));recentes.innerHTML=table(['OS','Cliente','Placa','Status','Total'],activeOrders().slice(0,5).map(o=>`<tr><td>#${o.numero}</td><td>${esc(nomeCliente(o))}</td><td>${esc(dadosVeiculo(o).placa||'Sem placa')}</td><td><span class="badge">${esc(o.status)}</span></td><td>${money(o.total)}</td></tr>`))}
function renderEmpresa(){Object.entries(db.empresa).forEach(([k,v])=>{if(empresaForm.elements[k])empresaForm.elements[k].value=v||''})}
function renderHistorico(orderId){const items=db.historicos.filter(h=>h.ordem_id===orderId);historicoOS.innerHTML=items.length?items.map(h=>`<div class="history-item"><strong>${dateBR(h.criado_em)}</strong><br>${esc(h.descricao)}</div>`).join(''):'<div class="empty">Nenhum histórico disponível.</div>'}
function renderItens(){const draw=arr=>arr.length?`<div class="section-table">${table(['Descrição','Qtd.','Valor unit.','Total',''],arr.map(x=>`<tr><td>${esc(x.descricao)}</td><td>${x.qtd}</td><td>${money(x.preco)}</td><td>${money(x.qtd*x.preco)}</td><td><button type="button" class="danger mini-btn" onclick="remItem('${x.id}')">Remover</button></td></tr>`))}</div>`:'<div class="empty">Nenhum item adicionado.</div>';listaServicosOS.innerHTML=draw(getServicos());listaProdutosOS.innerHTML=draw(getProdutos());totalServicos.value=money(totalServicosValue());totalProdutos.value=money(totalProdutosValue());valorDescontoServicos.value=money(descontoServicosValue());valorDescontoProdutos.value=money(descontoProdutosValue());totalGeralOS.value=money(totalGeralValue());valorParcelaOS.value=money(valorParcelaValue())}
function resetOS(){editingOrderId=null;editingOrderId.value='';osDialogTitle.textContent='Nova ordem de serviço';duplicateBtn.classList.add('hidden');deleteBtn.classList.add('hidden');numeroVisual.value=nextNumeroOS();descontoServicosPercentual.value=0;descontoProdutosPercentual.value=0;parcelasOS.value=1;itensTemp=[];historicoOS.innerHTML='<div class="empty">Nenhum histórico disponível.</div>';renderItens()}
function fillOrder(o){editingOrderId=o.id;document.getElementById('editingOrderId').value=o.id;osDialogTitle.textContent=`Editar ordem de serviço #${o.numero}`;duplicateBtn.classList.remove('hidden');deleteBtn.classList.remove('hidden');numeroVisual.value=o.numero;osForm.elements.tipoOS.value=o.tipo_os||'Ordem de Serviço';osForm.elements.clienteId.value=o.cliente_id||'';osForm.elements.clienteNome.value=o.cliente_nome||'';osForm.elements.clienteTelefone.value=o.cliente_telefone||'';osForm.elements.clienteDocumento.value=o.cliente_documento||'';osForm.elements.veiculoId.value=o.veiculo_id||'';osForm.elements.placaAvulsa.value=o.placa_avulsa||'';osForm.elements.marcaAvulsa.value=o.marca_avulsa||'';osForm.elements.modeloAvulso.value=o.modelo_avulso||'';osForm.elements.anoAvulso.value=o.ano_avulso||'';osForm.elements.kmAvulsa.value=o.km_avulsa||'';osForm.elements.status.value=o.status||'Aberta';osForm.elements.previsao.value=o.previsao||'';osForm.elements.reclamacao.value=o.reclamacao||'';osForm.elements.diagnostico.value=o.diagnostico||'';descontoServicosPercentual.value=0;descontoProdutosPercentual.value=0;parcelasOS.value=1;itensTemp=(o.itens||[]).map(i=>({id:i.id||id(),produto_id:i.produto_id||null,tipo:i.tipo,descricao:i.descricao,qtd:Number(i.quantidade||1),preco:Number(i.preco||0)}));renderHistorico(o.id);renderItens();osDialog.showModal()}
window.openEditOS=id=>{const o=db.ordens.find(x=>x.id===id);if(o)fillOrder(o)};
window.updateStatus=async(id,status)=>{const {error}=await supabaseClient.from('ordens_servico').update({status}).eq('id',id);if(error){alert(error.message);return}await supabaseClient.from('historico_ordens').insert({ordem_id:id,descricao:`Status alterado para ${status}`,criado_por:currentUser?.id||null});refreshData()};
window.deleteOS=async(id)=>{if(!confirm('Deseja excluir esta ordem?'))return;const {error}=await supabaseClient.from('ordens_servico').update({status:'Excluída'}).eq('id',id);if(error){alert(error.message);return}await supabaseClient.from('historico_ordens').insert({ordem_id:id,descricao:'Ordem excluída da lista principal',criado_por:currentUser?.id||null});refreshData()};
window.duplicateOS=async(id)=>{const o=db.ordens.find(x=>x.id===id);if(!o)return;const novoNumero=nextNumeroOS();const payload={...o,numero:novoNumero,status:'Aberta'};delete payload.id;delete payload.itens;const created=await supabaseClient.from('ordens_servico').insert(payload).select().single();if(created.error){alert(created.error.message);return}if(o.itens?.length){await supabaseClient.from('itens_ordem_servico').insert(o.itens.map(i=>({ordem_id:created.data.id,produto_id:i.produto_id,tipo:i.tipo,descricao:i.descricao,quantidade:i.quantidade,preco:i.preco,total:i.total}))) }await supabaseClient.from('historico_ordens').insert({ordem_id:created.data.id,descricao:`OS duplicada da ordem ${o.numero}`,criado_por:currentUser?.id||null});refreshData()};
document.querySelectorAll('.nav-btn').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav-btn,.page').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById(b.dataset.page).classList.add('active')});document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.open).showModal());document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());document.querySelectorAll('[data-open-os]').forEach(b=>b.onclick=()=>{osForm.reset();osForm.elements.veiculoId.innerHTML='<option value="">Preencher diretamente</option>';resetOS();osDialog.showModal()});
authForm.onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));const {error}=await supabaseClient.auth.signInWithPassword({email:d.email,password:d.senha});if(error)alert(error.message)};registerBtn.onclick=async()=>{const d=Object.fromEntries(new FormData(authForm));const {error}=await supabaseClient.auth.signUp({email:d.email,password:d.senha,options:{data:{nome:'Administrador Oficina Club'}}});if(error)alert(error.message)};logoutBtn.onclick=async()=>{await supabaseClient.auth.signOut()};
clienteForm.onsubmit=async e=>{e.preventDefault();const {error}=await supabaseClient.from('clientes').insert(Object.fromEntries(new FormData(e.target)));if(error){alert(error.message);return}e.target.reset();clienteDialog.close();refreshData()};
veiculoForm.onsubmit=async e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.target));const payload={...o,placa:(o.placa||'').toUpperCase(),cliente_id:o.clienteId,km:o.km?Number(o.km):null};delete payload.clienteId;const {error}=await supabaseClient.from('veiculos').insert(payload);if(error){alert(error.message);return}e.target.reset();veiculoDialog.close();refreshData()};
produtoForm.onsubmit=async e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.target));const {error}=await supabaseClient.from('produtos').insert({...o,preco:Number(o.preco),estoque:Number(o.estoque)});if(error){alert(error.message);return}e.target.reset();produtoDialog.close();refreshData()};
empresaForm.onsubmit=async e=>{e.preventDefault();const payload=Object.fromEntries(new FormData(e.target));const row=db.empresa.id?await supabaseClient.from('empresas').update(payload).eq('id',db.empresa.id):await supabaseClient.from('empresas').insert(payload);if(row.error){alert(row.error.message);return}refreshData()};
osForm.elements.clienteId.onchange=e=>{const c=cliente(e.target.value),vs=db.veiculos.filter(v=>v.cliente_id===e.target.value);osForm.elements.veiculoId.innerHTML='<option value="">Preencher diretamente</option>'+vs.map(v=>`<option value="${v.id}">${esc(v.placa)} - ${esc(v.marca)} ${esc(v.modelo)}</option>`).join('');if(c.id){osForm.elements.clienteNome.value=c.nome||'';osForm.elements.clienteTelefone.value=c.telefone||'';osForm.elements.clienteDocumento.value=c.documento||''}};
osForm.elements.veiculoId.onchange=e=>{const v=veiculo(e.target.value);if(v.id){osForm.elements.placaAvulsa.value=v.placa||'';osForm.elements.marcaAvulsa.value=v.marca||'';osForm.elements.modeloAvulso.value=v.modelo||'';osForm.elements.anoAvulso.value=v.ano||'';osForm.elements.kmAvulsa.value=v.km||''}};
addServicoCadastro.onclick=()=>{const p=db.produtos.find(x=>x.id===itemCatalogoServico.value);if(!p)return;itensTemp.push({id:id(),produto_id:p.id,tipo:'Serviço',descricao:p.descricao,qtd:Number(itemQtdServico.value||1),preco:Number(p.preco)});renderItens()};
addProdutoCadastro.onclick=()=>{const p=db.produtos.find(x=>x.id===itemCatalogoProduto.value);if(!p)return;itensTemp.push({id:id(),produto_id:p.id,tipo:'Peça',descricao:p.descricao,qtd:Number(itemQtdProduto.value||1),preco:Number(p.preco)});renderItens()};
addServicoManual.onclick=()=>{const d=(manualServicoDescricao.value||'').trim();if(!d)return alert('Digite a descrição do serviço.');itensTemp.push({id:id(),produto_id:null,tipo:'Serviço',descricao:d,qtd:Number(manualServicoQtd.value||1),preco:Number(manualServicoPreco.value||0)});manualServicoDescricao.value='';manualServicoQtd.value=1;manualServicoPreco.value='';renderItens()};
addProdutoManual.onclick=()=>{const d=(manualProdutoDescricao.value||'').trim();if(!d)return alert('Digite a descrição do produto.');itensTemp.push({id:id(),produto_id:null,tipo:'Peça',descricao:d,qtd:Number(manualProdutoQtd.value||1),preco:Number(manualProdutoPreco.value||0)});manualProdutoDescricao.value='';manualProdutoQtd.value=1;manualProdutoPreco.value='';renderItens()};
window.remItem=i=>{itensTemp=itensTemp.filter(x=>x.id!==i);renderItens()};
descontoServicosPercentual.oninput=renderItens;descontoProdutosPercentual.oninput=renderItens;parcelasOS.oninput=renderItens;
osForm.onsubmit=async e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.target));if(!o.clienteId&&!o.clienteNome.trim()&&!o.placaAvulsa.trim()&&!o.modeloAvulso.trim())return alert('Informe ao menos o nome do cliente ou algum dado do veículo.');const total=totalGeralValue();const payload={numero:editingOrderId?numeroVisual.value:nextNumeroOS(),tipo_os:o.tipoOS||'Ordem de Serviço',cliente_id:o.clienteId||null,veiculo_id:o.veiculoId||null,cliente_nome:o.clienteNome||null,cliente_telefone:o.clienteTelefone||null,cliente_documento:o.clienteDocumento||null,placa_avulsa:(o.placaAvulsa||'').toUpperCase()||null,marca_avulsa:o.marcaAvulsa||null,modelo_avulso:o.modeloAvulso||null,ano_avulso:o.anoAvulso||null,km_avulsa:o.kmAvulsa?Number(o.kmAvulsa):null,status:o.status,previsao:o.previsao||null,reclamacao:o.reclamacao,diagnostico:o.diagnostico||null,total,criado_por:currentUser?.id||null};let ordemId;if(editingOrderId){const upd=await supabaseClient.from('ordens_servico').update(payload).eq('id',editingOrderId).select().single();if(upd.error){alert(upd.error.message);return}ordemId=editingOrderId;await supabaseClient.from('itens_ordem_servico').delete().eq('ordem_id',editingOrderId);await supabaseClient.from('historico_ordens').insert({ordem_id:editingOrderId,descricao:'OS editada',criado_por:currentUser?.id||null})}else{const created=await supabaseClient.from('ordens_servico').insert(payload).select().single();if(created.error){alert(created.error.message);return}ordemId=created.data.id;await supabaseClient.from('historico_ordens').insert({ordem_id:ordemId,descricao:`OS ${payload.numero} criada com status ${payload.status}`,criado_por:currentUser?.id||null})}if(itensTemp.length){const ins=await supabaseClient.from('itens_ordem_servico').insert(itensTemp.map(x=>({ordem_id:ordemId,produto_id:x.produto_id,tipo:x.tipo,descricao:x.descricao,quantidade:x.qtd,preco:x.preco,total:x.qtd*x.preco})));if(ins.error){alert(ins.error.message);return}}if(o.formaPagamento){await supabaseClient.from('pagamentos').delete().eq('ordem_id',ordemId);await supabaseClient.from('pagamentos').insert({ordem_id:ordemId,forma:`${o.formaPagamento}${Number(o.parcelas||1)>1?` - ${o.parcelas}x`:''}`,valor:total,observacao:`${Number(o.parcelas||1)} parcela(s) de ${money(valorParcelaValue())}`})}osDialog.close();osForm.reset();resetOS();refreshData()};
backupBtn.onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(db,null,2)],{type:'application/json'}));a.download=`backup-oficina-club-${todayStamp()}.json`;a.click();URL.revokeObjectURL(a.href)};
window.printOS=i=>{const o=db.ordens.find(x=>x.id===i),v=dadosVeiculo(o),e=db.empresa,itens=(o.itens||[]).map(x=>`<tr><td>${esc(x.descricao)}</td><td>${x.quantidade}</td><td>${money(x.preco)}</td><td>${money(x.total)}</td></tr>`).join(''),w=open('','_blank');w.document.write(`<!doctype html><html><head><title>OS ${o.numero}</title></head><body><h1>${esc(e.nome)}</h1><h2>Ordem de Serviço ${o.numero}</h2><p>${esc(nomeCliente(o))}</p><table border="1"><tr><th>Descrição</th><th>Qtd</th><th>Valor</th><th>Total</th></tr>${itens}</table><h3>Total: ${money(o.total)}</h3><script>window.onload=()=>window.print()<\/script></body></html>`);w.document.close()};
async function handleSession(){const {data:{session}}=await supabaseClient.auth.getSession();currentUser=session?.user||null;authScreen.classList.toggle('hidden',!!session);appShell.classList.toggle('hidden',!session);logoutBtn.classList.toggle('hidden',!session);if(session)await refreshData()}
supabaseClient.auth.onAuthStateChange(()=>handleSession());handleSession();